/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kehadiranPegawai;

import java.text.ParseException;
 import java.text.SimpleDateFormat;
 import java.util.Date;
 import java.util.List;
 import javax.swing.JOptionPane;
 import javax.swing.table.DefaultTableModel;
 import javax.swing.text.MaskFormatter;
 import kehadiranPegawai.dao.KehadiranDAO;
 import kehadiranPegawai.dao.PegawaiDAO;
 import kehadiranPegawai.dbase.KoneksiDatabase;
 import kehadiranPegawai.entities.Kehadiran;
 import java.sql.Time;
 import java.util.Calendar;
 import javax.swing.JFormattedTextField;

/**
 *
 * @author ASUS
 */
public class daftarHadir extends javax.swing.JFrame {

    /**
     * Creates new form daftarHadir
     */
    
    private KehadiranDAO kehadiranDAO;
    private DefaultTableModel modelTabel;
    private SimpleDateFormat dateFormat;
    private SimpleDateFormat timeFormat;
    private PegawaiDAO pegawaiDAO;
    
    public daftarHadir(KoneksiDatabase koneksiDatabase) {
        initComponents();
        
    kehadiranDAO = new KehadiranDAO(koneksiDatabase.getKoneksi());
       
    // Buat instance PegawaiDAO
    pegawaiDAO = new PegawaiDAO(koneksiDatabase.getKoneksi()); 

    // Atur format tanggal dan waktu
    dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    timeFormat = new SimpleDateFormat("HH:mm");

    // Inisialisasi model tabel
    modelTabel = (DefaultTableModel) jTable1.getModel();
    modelTabel.setColumnIdentifiers(new String[]{"ID Pegawai", "Nama", "Tanggal", "Jam Masuk", "Jam Keluar", "Durasi Kerja"});


    tampilkanDataKehadiran(); // Tampilkan data kehadiran awal
    
    }
    
    private void tampilkanDataKehadiran() {
     modelTabel.setRowCount(0); // Bersihkan tabel

     List<Kehadiran> daftarKehadiran = kehadiranDAO.getAllKehadiran();
     for (Kehadiran kehadiran : daftarKehadiran) {
         
         long timestamp = kehadiran.getTanggal().getTime(); 
         Date tanggalUtil = new Date(timestamp);
         
         Object[] rowData = {
             kehadiran.getIdPegawai(),
             pegawaiDAO.getPegawaiById(kehadiran.getIdPegawai()).getNama(), // Ambil nama dari database
             dateFormat.format(tanggalUtil),
             timeFormat.format(kehadiran.getJamMasuk()),
             timeFormat.format(kehadiran.getJamKeluar()),
             String.format("%.0f jam", kehadiran.getDurasiKerja()) // Format durasi kerja (contoh: 7 jam)
         };
         modelTabel.addRow(rowData);
     }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaHadir = new javax.swing.JTextField();
        idHadir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        simpanHadir = new javax.swing.JButton();
        back = new javax.swing.JButton();
        inputJamMasuk = new javax.swing.JTextField();
        inputMenitMasuk = new javax.swing.JTextField();
        inputJamKeluar = new javax.swing.JTextField();
        inputMenitKeluar = new javax.swing.JTextField();
        inpuTahun = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inputBulan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        inputTanggal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("KEHADIRAN PEGAWAI");

        jLabel2.setText("Nama :");

        jLabel3.setText("ID Pegawai :");

        namaHadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaHadirActionPerformed(evt);
            }
        });

        idHadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idHadirActionPerformed(evt);
            }
        });

        jLabel4.setText("Tanggal :");

        jLabel5.setText("Jam Masuk :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText(":");

        jLabel7.setText("Jam Keluar :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText(":");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Tanggal", "Jam Masuk", "Jam Keluar"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        simpanHadir.setText("Simpan");
        simpanHadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanHadirActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        inputJamMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJamMasukActionPerformed(evt);
            }
        });

        inputMenitMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMenitMasukActionPerformed(evt);
            }
        });

        inputJamKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJamKeluarActionPerformed(evt);
            }
        });

        inputMenitKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMenitKeluarActionPerformed(evt);
            }
        });

        inpuTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpuTahunActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("-");

        inputBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBulanActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("-");

        inputTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTanggalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel12.setText("*input tanggal : YYYY-MM-DD");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel13.setText("*input jam -- Jam : Menit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaHadir)
                                    .addComponent(idHadir))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inpuTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputMenitKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputMenitMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(609, 609, 609)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(simpanHadir)
                            .addComponent(back)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jLabel3)
                    .addContainerGap(599, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(inputJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputMenitMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(inputJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputMenitKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idHadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaHadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inpuTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(inputBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(inputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(simpanHadir))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jLabel3)
                    .addContainerGap(350, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idHadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idHadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idHadirActionPerformed

    private void simpanHadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanHadirActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil data dari input
            int idPegawai = Integer.parseInt(idHadir.getText());
            String namaPegawai = namaHadir.getText();
            int tahun = Integer.parseInt(inpuTahun.getText()); 
            int bulan = Integer.parseInt(inputBulan.getText());
            int tanggal = Integer.parseInt(inputTanggal.getText()); 
            int jamMasuk = Integer.parseInt(inputJamMasuk.getText());
            int menitMasuk = Integer.parseInt(inputMenitMasuk.getText());
            int jamKeluar = Integer.parseInt(inputJamKeluar.getText());
            int menitKeluar = Integer.parseInt(inputMenitKeluar.getText());
            
            kehadiranPegawai.entities.Pegawai pegawai = pegawaiDAO.getPegawaiById(idPegawai);
            if (pegawai == null) {
                throw new IllegalArgumentException("ID Pegawai tidak ditemukan.");
            }

            // 2. Validasi input jam dan menit 
            if (jamMasuk < 0 || jamMasuk > 23 || menitMasuk < 0 || menitMasuk > 59 ||
                jamKeluar < 0 || jamKeluar > 23 || menitKeluar < 0 || menitKeluar > 59) {
                throw new IllegalArgumentException("Format jam atau menit tidak valid.");
            }

            // 3. Validasi input tanggal (opsional, tetapi disarankan)
            if (tahun < 1900 || tahun > 2100 || bulan < 1 || bulan > 12 || tanggal < 1 || tanggal > 31) {
                throw new IllegalArgumentException("Format tanggal tidak valid.");
            }

            // 4. Buat objek Date
            Calendar cal = Calendar.getInstance();
            cal.set(Calendar.YEAR, tahun);
            cal.set(Calendar.MONTH, bulan - 1); // Bulan di Calendar dimulai dari 0
            cal.set(Calendar.DAY_OF_MONTH, tanggal);
            Date tanggalDate = cal.getTime();

            // 5. Konversi ke java.sql.Date
            java.sql.Date sqlTanggal = new java.sql.Date(tanggalDate.getTime());

            // 6. Buat objek Time untuk jam masuk dan jam keluar
            Time jamMasukTime = new Time(jamMasuk, menitMasuk, 0);
            Time jamKeluarTime = new Time(jamKeluar, menitKeluar, 0);

            // 7. Hitung durasi kerja (dalam jam)
            long durasiMillis = jamKeluarTime.getTime() - jamMasukTime.getTime();
            double durasiJam = durasiMillis / (1000.0 * 60 * 60);

            // 8. objek Kehadiran
            Kehadiran kehadiran = new Kehadiran(0, idPegawai, sqlTanggal, jamMasukTime, jamKeluarTime, durasiJam);

            // 9. Simpan data ke database
            kehadiranDAO.catatKehadiran(kehadiran);
            JOptionPane.showMessageDialog(this, "Data kehadiran berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // 10. Refresh tabel dan bersihkan input
            tampilkanDataKehadiran();
            idHadir.setText("");
            namaHadir.setText("");
            inpuTahun.setText(""); 
            inputBulan.setText(""); 
            inputTanggal.setText(""); 
            inputJamMasuk.setText("");
            inputMenitMasuk.setText("");
            inputJamKeluar.setText("");
            inputMenitKeluar.setText("");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID Pegawai, jam, dan menit harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data kehadiran: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    
 
    }//GEN-LAST:event_simpanHadirActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void namaHadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaHadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaHadirActionPerformed

    private void inputJamMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJamMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJamMasukActionPerformed

    private void inputMenitMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMenitMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMenitMasukActionPerformed

    private void inputJamKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJamKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJamKeluarActionPerformed

    private void inputMenitKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMenitKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMenitKeluarActionPerformed

    private void inpuTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpuTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpuTahunActionPerformed

    private void inputBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBulanActionPerformed

    private void inputTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTanggalActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField idHadir;
    private javax.swing.JTextField inpuTahun;
    private javax.swing.JTextField inputBulan;
    private javax.swing.JTextField inputJamKeluar;
    private javax.swing.JTextField inputJamMasuk;
    private javax.swing.JTextField inputMenitKeluar;
    private javax.swing.JTextField inputMenitMasuk;
    private javax.swing.JTextField inputTanggal;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namaHadir;
    private javax.swing.JButton simpanHadir;
    // End of variables declaration//GEN-END:variables
}
