/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kehadiranPegawai;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kehadiranPegawai.dao.AbsensiDAO;
import kehadiranPegawai.dao.PegawaiDAO;
import kehadiranPegawai.dbase.KoneksiDatabase;
import kehadiranPegawai.entities.Absensi;
import java.util.Calendar;
import kehadiranPegawai.entities.Pegawai;

/**
 *
 * @author ASUS
 */
public class daftarAbsen extends javax.swing.JFrame {

    /**
     * Creates new form daftarAbsen
     */
        private AbsensiDAO absensiDAO;
        private DefaultTableModel modelTabel;
        private SimpleDateFormat dateFormat;
        private PegawaiDAO pegawaiDAO;
        
    public daftarAbsen(KoneksiDatabase koneksiDatabase) {
        initComponents();
        
        // Inisialisasi AbsensiDAO dan PegawaiDAO
        absensiDAO = new AbsensiDAO(koneksiDatabase.getKoneksi());
        pegawaiDAO = new PegawaiDAO(koneksiDatabase.getKoneksi());

        // Atur format tanggal 
        dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        // Inisialisasi model tabel
        modelTabel = (DefaultTableModel) jTable1.getModel();
        modelTabel.setColumnIdentifiers(new String[]{"ID Pegawai", "Nama", "Tanggal", "Alasan"}); 

        tampilkanDataAbsen();
        
    }
    
    private void tampilkanDataAbsen() {
        modelTabel.setRowCount(0); // Bersihkan tabel

        List<Absensi> daftarAbsen = absensiDAO.getAllAbsensi();
        for (Absensi absensi : daftarAbsen) {
            Pegawai pegawai = pegawaiDAO.getPegawaiById(absensi.getIdPegawai());
            Object[] rowData = {
                absensi.getIdPegawai(),
                pegawai.getNama(),
                dateFormat.format(absensi.getTanggal()),
                absensi.getAlasan()
            };
            modelTabel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idAbsen = new javax.swing.JTextField();
        namaAbsen = new javax.swing.JTextField();
        inputTahunAbsen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputBulanAbsen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputTanggalAbsen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alasanComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        simpanAbsen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ABSENSI PEGAWAI");

        jLabel2.setText("ID Pegawai :");

        jLabel3.setText("Nama :");

        jLabel4.setText("Tanggal : ");

        inputTahunAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTahunAbsenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("-");

        inputBulanAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBulanAbsenActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("-");

        inputTanggalAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTanggalAbsenActionPerformed(evt);
            }
        });

        jLabel7.setText("Alasan :");

        alasanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Izin", "Sakit", "Cuti" }));
        alasanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alasanComboBoxActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Tanggal", "Alasan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        simpanAbsen.setText("Simpan");
        simpanAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanAbsenActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel8.setText("*input tanggal : YYYY-MM-DD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Back))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputTahunAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputBulanAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputTanggalAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(namaAbsen)
                                            .addComponent(idAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(alasanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13))
                                            .addComponent(simpanAbsen, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(246, 246, 246)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(alasanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputTahunAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBulanAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTanggalAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanAbsen))
                .addGap(8, 8, 8)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Back)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTahunAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTahunAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTahunAbsenActionPerformed

    private void inputBulanAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBulanAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBulanAbsenActionPerformed

    private void inputTanggalAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTanggalAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTanggalAbsenActionPerformed

    private void alasanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alasanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alasanComboBoxActionPerformed

    private void simpanAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanAbsenActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Ambil data dari input
            int idPegawai = Integer.parseInt(idAbsen.getText());
            String namaPegawai = namaAbsen.getText(); 
            int tahun = Integer.parseInt(inputTahunAbsen.getText());
            int bulan = Integer.parseInt(inputBulanAbsen.getText());
            int tanggal = Integer.parseInt(inputTanggalAbsen.getText());
            String alasan = alasanComboBox.getSelectedItem().toString();

            // 2. Validasi ID Pegawai
            Pegawai pegawai = pegawaiDAO.getPegawaiById(idPegawai);
            if (pegawai == null) {
                throw new IllegalArgumentException("ID Pegawai tidak ditemukan.");
            }

            // 3. Validasi input tanggal (opsional)
            if (tahun < 1900 || tahun > 2100 || bulan < 1 || bulan > 12 || tanggal < 1 || tanggal > 31) {
                throw new IllegalArgumentException("Format tanggal tidak valid.");
            }

            // 4. Buat objek Date
            Calendar cal = Calendar.getInstance();
            cal.set(Calendar.YEAR, tahun);
            cal.set(Calendar.MONTH, bulan - 1); // Bulan di Calendar dimulai dari 0
            cal.set(Calendar.DAY_OF_MONTH, tanggal);
            Date tanggalDate = cal.getTime();

            // 5. Konversi ke java.sql.Date
            java.sql.Date sqlTanggal = new java.sql.Date(tanggalDate.getTime());

            // 6. Buat objek Absensi (tanpa jenisAbsensi)
            Absensi absensi = new Absensi(0, idPegawai, sqlTanggal, alasan);

            // 7. Simpan data ke database
            absensiDAO.tambahAbsensi(absensi);
            JOptionPane.showMessageDialog(this, "Data absensi berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // 8. Refresh tabel dan bersihkan input
            tampilkanDataAbsen();
            idAbsen.setText("");
            namaAbsen.setText("");
            inputTahunAbsen.setText("");
            inputBulanAbsen.setText("");
            inputTanggalAbsen.setText("");
            alasanComboBox.setSelectedIndex(0); 

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID Pegawai, tahun, bulan, dan tanggal harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data absensi: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_simpanAbsenActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> alasanComboBox;
    private javax.swing.JTextField idAbsen;
    private javax.swing.JTextField inputBulanAbsen;
    private javax.swing.JTextField inputTahunAbsen;
    private javax.swing.JTextField inputTanggalAbsen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namaAbsen;
    private javax.swing.JButton simpanAbsen;
    // End of variables declaration//GEN-END:variables
}
